# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "canada_provinces_select"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["PagerDuty"]
  s.date = "2012-04-18"
  s.description = "Canada Provinces select Rails plugin"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/canada_provinces_select.rb"
  ]
  s.homepage = "https://github.com/vivrass/canada-provinces-select"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Canada Provinces select Rails plugin"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 1.2"])
    else
      s.add_dependency(%q<rails>, [">= 1.2"])
    end
  else
    s.add_dependency(%q<rails>, [">= 1.2"])
  end
end

